(function () {
  const $ = (s) => document.querySelector(s);
  const $verses = $('#verses'), $hover=$('#hovercard'), $prev=$('#btnPrev'), $next=$('#btnNext'), $chSel=$('#chSelect'), $canon=$('#canonSelect'), $book=$('#bookSelect'), $title=$('#pageTitle'), $crumbs=$('#crumbs');
  const $dictToggle=$('#dictToggle'), $dictReveal=$('#dictReveal'), $dictQuery=$('#dictQuery'), $dictBody=$('#dictBody');
  const status=(m)=>{$verses.innerHTML=`<p class="muted">${m}</p>`;}, esc=(s)=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function canonFromPath(){const p=location.pathname.split('/').filter(Boolean);const i=p.indexOf('israelite-research');const c=(i>=0&&p[i+1])?p[i+1]:'newtestament';return/^(tanakh|newtestament|apocrypha)$/i.test(c)?c.toLowerCase():'newtestament';}
  function ctxFromUrl(){const q=new URLSearchParams(location.search);return{canon:canonFromPath(),book:(q.get('book')||'').toLowerCase().trim(),chapter:parseInt(q.get('ch')||q.get('c')||'1',10)||1};}
  function chapterHref(c,b,ch){return`/israelite-research/${c}/chapter.html?book=${b}&ch=${ch}`;}
  function cap(slug){return slug.split('-').map((t,i)=>i===0&&/^\d+$/.test(t)?t:t.charAt(0).toUpperCase()+t.slice(1)).join(' ');}
  const CANON_ORDER={tanakh:['genesis','exodus','leviticus','numbers','deuteronomy','joshua','judges','ruth','1-samuel','2-samuel','1-kings','2-kings','1-chronicles','2-chronicles','ezra','nehemiah','esther','job','psalms','proverbs','ecclesiastes','song-of-solomon','isaiah','jeremiah','lamentations','ezekiel','daniel','hosea','joel','amos','obadiah','jonah','micah','nahum','habakkuk','zephaniah','haggai','zechariah','malachi'],newtestament:['matthew','mark','luke','john','acts','romans','1-corinthians','2-corinthians','galatians','ephesians','philippians','colossians','1-thessalonians','2-thessalonians','1-timothy','2-timothy','titus','philemon','hebrews','james','1-peter','2-peter','1-john','2-john','3-john','jude','revelation'],apocrypha:['tobit','judith','additions-to-esther','wisdom','sirach','baruch','letter-of-jeremiah','prayer-of-azariah','susanna','bel-and-the-dragon','1-maccabees','2-maccabees','1-esdras','2-esdras','prayer-of-manasseh']};
  async function loadBooksJson(c){try{const r=await fetch(`/israelite-research/data/${c}/books.json`);if(r.ok)return await r.json();}catch{}const m={};(CANON_ORDER[c]||[]).forEach(s=>m[s]=150);return m;}
  function updateHeader(ctx){if($title)$title.textContent=`${cap(ctx.book||'')} (Chapter ${ctx.chapter})`;if($crumbs)$crumbs.textContent=`${cap(ctx.canon)} → ${cap(ctx.book||'')} → ${ctx.chapter}`;}
  function updateChSel(t,c){$chSel.innerHTML='';for(let i=1;i<=t;i++){const o=document.createElement('option');o.value=String(i);o.textContent=`Chapter ${i}`;if(i===c)o.selected=true;$chSel.appendChild(o);}}
  function wireNav(ctx,t){const total=t[ctx.book]||t[Object.keys(t)[0]]||150;updateHeader(ctx);updateChSel(total,ctx.chapter);$prev.onclick=()=>location.href=chapterHref(ctx.canon,ctx.book,Math.max(1,ctx.chapter-1));$next.onclick=()=>location.href=chapterHref(ctx.canon,ctx.book,Math.min(total,ctx.chapter+1));$chSel.onchange=e=>location.href=chapterHref(ctx.canon,ctx.book,parseInt(e.target.value,10));$canon.value=ctx.canon;$canon.onchange=()=>{const tgt=$canon.value;const order=CANON_ORDER[tgt]||[];const next=order.includes(ctx.book)?ctx.book:order[0]||'matthew';location.href=chapterHref(tgt,next,1);};const order=Object.keys(t).length?Object.keys(t):(CANON_ORDER[ctx.canon]||[]);$book.innerHTML='';order.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=cap(s);if(s===ctx.book)o.selected=true;$book.appendChild(o);});$book.onchange=e=>location.href=chapterHref(ctx.canon,e.target.value,1);}
  function renderVerses(j,ctx){const vs=Array.isArray(j?.verses)?j.verses:[];if(!vs.length){status('Verses coming soon.');return;}const f=document.createDocumentFragment();vs.forEach(v=>{const a=document.createElement('article');a.className='verse';a.id=`v${v.v}`;a.setAttribute('data-verse',v.v);const n=document.createElement('span');n.className='vnum';n.textContent=v.v;const t=document.createElement('span');t.className='vtext';t.textContent=v.t||'';const acts=document.createElement('div');acts.className='v-actions';const bc=document.createElement('button');bc.textContent='Copy';bc.onclick=()=>navigator.clipboard?.writeText(`${cap(ctx.book)} ${ctx.chapter}:${v.v} ${v.t||''}`);const bs=document.createElement('button');bs.textContent='Link';bs.onclick=()=>navigator.clipboard?.writeText(`${location.origin}${chapterHref(ctx.canon,ctx.book,ctx.chapter)}#v${v.v}`);acts.appendChild(bc);acts.appendChild(bs);a.appendChild(n);a.appendChild(t);a.appendChild(acts);f.appendChild(a);});$verses.innerHTML='';$verses.appendChild(f);}
  async function fetchFirstOk(urls){for(const u of urls){try{const r=await fetch(u);if(r.ok)return await r.json();}catch{}}return null;}
  async function loadChapter(ctx){if(!ctx.book){ctx.book=(CANON_ORDER[ctx.canon]||[])[0]||'matthew';history.replaceState(null,'',chapterHref(ctx.canon,ctx.book,ctx.chapter));}const totals=await loadBooksJson(ctx.canon);wireNav(ctx,totals);const cands=[`/israelite-research/data/${ctx.canon}/${ctx.book}/${ctx.chapter}.json`];const j=await fetchFirstOk(cands);j?renderVerses(j,ctx):status('Verses coming soon.');}
  let EASTON=null;async function loadEaston(){if(EASTON)return EASTON;for(const u of['/israelite-research/data/dictionary/easton_dictionary.json','/israelite-research/data/easton_dictionary.json']){try{const r=await fetch(u);if(r.ok){EASTON=await r.json();return EASTON;}}catch{}}return{entries:[]};}
  function* eastonIter(db){if(Array.isArray(db)){for(const e of db)yield{h:e.headword||e.h||'',t:e.text||e.g||''};}else if(Array.isArray(db.entries)){for(const e of db.entries)yield{h:e.headword||e.h||'',t:e.text||e.g||''};}else if(db&&typeof db==='object'){for(const k in db)yield{h:k,t:db[k]};}}
  function wireDict(){$dictToggle.onclick=()=>{$dictReveal.style.maxHeight=$dictReveal.getAttribute('data-open')==='1'?'0':'100px';$dictReveal.setAttribute('data-open',$dictReveal.getAttribute('data-open')==='1'?'0':'1');$dictQuery.focus();};$dictQuery.onkeydown=async e=>{if(e.key==='Enter'){const q=$dictQuery.value.trim().toLowerCase();if(!q)return;$dictBody.innerHTML='<p class="muted">Searching…</p>';const db=await loadEaston();const hits=[];for(const e of eastonIter(db)){if(e.h.toLowerCase().includes(q)||e.t.toLowerCase().includes(q)){hits.push(e);if(hits.length>=50)break;}}$dictBody.innerHTML=hits.length?hits.map(e=>`<div><strong>${esc(e.h)}</strong> — ${esc(e.t)}</div>`).join(''):'<p class="muted">No results.</p>';}};}
  const ctx=ctxFromUrl();loadChapter(ctx);wireDict();
})();
