name: Deploy static site to Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug listing
        run: |
          set -euxo pipefail
          pwd
          ls -la
          find . -maxdepth 3 -type d -print

      # Ensure Pages doesn’t try to run Jekyll (you’re serving static files)
      - name: Disable Jekyll
        run: |
          set -euxo pipefail
          touch .nojekyll

      # Clean any stray backups so they don't confuse the deploy
      - name: Clean backup files
        run: |
          set -euxo pipefail
          find . -type f -name "*.bak*" -delete || true

      # Upload the WHOLE repo (your site lives under /israelite-research plus root HTML)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

